package application

import (
	"github.com/paguerre3/goddd/modules/player-couple/domain"
)

// UpsertPlayerUseCase registers a player or updates it if it already exists.
func (s *PlayerCoupleService) UpsertPlayerUseCase(inputPlayer domain.Player) (err error) {
	// Validate new player entries.
	newPlayer, err := domain.NewPlayer(s.idGen,
		inputPlayer.Email,
		inputPlayer.SocialSecurityNumber,
		inputPlayer.FirstName,
		inputPlayer.LastName,
		inputPlayer.Age)
	if err != nil {
		return err
	}

	// Check if the player already exists.
	var foundPlayer domain.Player
	if len(inputPlayer.ID) > 0 {
		// Reset the player ID if it was autogenerated.
		newPlayer.ID = inputPlayer.ID
		foundPlayer, err = s.playerRepo.FindByID(inputPlayer.ID)
	} else {
		foundPlayer, err = s.playerRepo.FindByEmail(inputPlayer.Email)
		if len(foundPlayer.ID) > 0 {
			// If playar was found by email ensure to reset ID if it was autogenerated.
			newPlayer.ID = foundPlayer.ID
		}
	}
	if err != nil {
		return err
	}

	// Ensure existing player isn't an empty struct:
	if len(foundPlayer.ID) > 0 {
		err = s.playerRepo.Update(*newPlayer)
	} else {
		err = s.playerRepo.Save(*newPlayer)
	}

	return err
}
