apiVersion: v1
# k8s config file type,
# Secret kind is usually stored in a secured pace
# different than the Depoyment respository
kind: Secret
metadata:
  # random name here
  name: mongodb-secret
  namespace: goddd
# Opaque is the default for arbitrary key/value pairs,
# other types include tls certificates
type: Opaque
data:
  # base64 encoded data
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: cGFzcw==
  # user and password added to the uri
  # mongodb://{user}:{password}@mongodb-service:27017
  MONGO_ADDR_V1: bW9uZ29kYjovL3Jvb3Q6cGFzc0Btb25nb2RiLXNlcnZpY2U6MjcwMTc=
  # mongodb://{user}:{password}@mongodb-service:27017/
  MONGO_ADDR_V2: bW9uZ29kYjovL3Jvb3Q6cGFzc0Btb25nb2RiLXNlcnZpY2U6MjcwMTcv