apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.password | b64enc }}
  MONGO_ADDR_V1: {{ .Values.mongodb.uri | b64enc }}